### ISSUE TITLE
Why the cryptic method names?

### ISSUE THREAD

**Issue by Prinzhorn** [isaachess/paypal-ec#3]
I mean, why call it `get_details` when `getExpressCheckoutDetails` would make a much better name and would lower the entry barrier? Basically the API documentation would shrink to "all PayPal API methods are supported" because all of them have the exact same method signature and the names and details can be found in the PayPal documentation.

**Comment by isaachess** [comment]
@sogko I just published the latest to npm. I haven't made any changes on this, but published the latest to npm. Please open a new issue if you'd like to see more changes.
